name:                illimat
version:             0.1.0.0
github:              "ewilden/illimat"
license:             BSD3
author:              "Evan Wildenhain"
maintainer:          "evan.wildenhain@gmail.com"
copyright:           "2020- Evan Wildenhain"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -fwarn-tabs
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
- -fwarn-unused-binds
- -fwarn-unused-imports
- -Wno-unused-top-binds
- -Wno-unused-matches

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ewilden/illimat#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- mtl
- lens
- sort
- random
- elm-bridge
- text-conversions
- aeson
- scotty
- bytestring
- wai-cors
- data-has
- lens-tutorial
- string-random
- more-containers
# - transformers-either 

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell
- ConstraintKinds
- FlexibleContexts
- TupleSections
- GeneralizedNewtypeDeriving

library:
  source-dirs: src

executables:
  illimat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - illimat
  schemagen:
    main:               Main.hs
    source-dirs:        schemagen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - illimat

# tests:
#   illimat-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - illimat
